# syntax=docker/dockerfile:1.4
FROM --platform=$BUILDPLATFORM python:3.9.10-alpine AS builder

WORKDIR /app

COPY requirements.txt /app
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r requirements.txt

COPY . /app

ENTRYPOINT ["python3"]
CMD ["app.py"]

FROM builder as dev-envs

RUN <<EOF
apk update
apk add git
apk add make automake gcc g++ subversion python3-dev
EOF

RUN <<EOF
addgroup -S docker
adduser -S --shell /bin/bash --ingroup docker vscode
EOF
# install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /


#FROM tiangolo/uwsgi-nginx-flask:python3.7
#COPY ./ /
#RUN pip install -r requirements.txt
